apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_key
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    name: http
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_service
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
