apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_key
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps
  - port: 30000
    name: ftps-0
  - port: 30001
    name: ftps-1
  - port: 30002
    name: ftps-2
  - port: 30003
    name: ftps-3
  - port: 30004
    name: ftps-4
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_service
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000
        - containerPort: 30001
        - containerPort: 30002
        - containerPort: 30003
        - containerPort: 30004
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 4
          periodSeconds: 4
